# Generated by Django 2.2.5 on 2019-09-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snippets.Language', verbose_name='language')),
            ],
            options={
                'verbose_name': 'Workbook',
                'verbose_name_plural': 'Workbooks',
                'db_table': 'snippets_workbooks',
                'ordering': ['name'],
            },
        ),
    ]
