# Generated by Django 2.2.5 on 2019-09-14 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('code', models.TextField(blank=True, verbose_name='code')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snippets.Folder', verbose_name='folder')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snippets.Language', verbose_name='language')),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
                'db_table': 'snippets_snippets',
                'ordering': ['name'],
                'unique_together': {('folder', 'name')},
            },
        ),
    ]
