# Generated by Django 2.2.5 on 2019-09-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_snippet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['workbook', 'order', 'name'], 'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['folder', 'order', 'name'], 'verbose_name': 'Snippet', 'verbose_name_plural': 'Snippets'},
        ),
    ]
