# Generated by Django 2.2.5 on 2019-09-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='lexer',
            field=models.CharField(default='text', max_length=255, verbose_name='lexer'),
        ),
    ]
