# Generated by Django 2.2.5 on 2019-09-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_admin_list_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlistdisplay',
            options={'ordering': ['model', 'order'], 'verbose_name': 'Admin List Display', 'verbose_name_plural': 'Admin List Display'},
        ),
        migrations.AlterModelOptions(
            name='adminlistdisplaylink',
            options={'ordering': ['model', 'order'], 'verbose_name': 'Admin List Display Link', 'verbose_name_plural': 'Admin List Display Links'},
        ),
        migrations.AlterModelOptions(
            name='adminlistfilter',
            options={'ordering': ['model', 'order'], 'verbose_name': 'Admin List Filter', 'verbose_name_plural': 'Admin List Filters'},
        ),
        migrations.AlterField(
            model_name='adminlistdisplay',
            name='model',
            field=models.CharField(choices=[('AdminListDisplayAdmin', 'AdminListDisplayAdmin'), ('AdminListDisplayLinkAdmin', 'AdminListDisplayLinkAdmin'), ('AdminListFilterAdmin', 'AdminListFilterAdmin'), ('FolderAdmin', 'FolderAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('SnippetAdmin', 'SnippetAdmin'), ('WorkbookAdmin', 'WorkbookAdmin')], max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='adminlistdisplaylink',
            name='model',
            field=models.CharField(choices=[('AdminListDisplayAdmin', 'AdminListDisplayAdmin'), ('AdminListDisplayLinkAdmin', 'AdminListDisplayLinkAdmin'), ('AdminListFilterAdmin', 'AdminListFilterAdmin'), ('FolderAdmin', 'FolderAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('SnippetAdmin', 'SnippetAdmin'), ('WorkbookAdmin', 'WorkbookAdmin')], max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='adminlistfilter',
            name='model',
            field=models.CharField(choices=[('AdminListDisplayAdmin', 'AdminListDisplayAdmin'), ('AdminListDisplayLinkAdmin', 'AdminListDisplayLinkAdmin'), ('AdminListFilterAdmin', 'AdminListFilterAdmin'), ('FolderAdmin', 'FolderAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('SnippetAdmin', 'SnippetAdmin'), ('WorkbookAdmin', 'WorkbookAdmin')], max_length=255, verbose_name='model'),
        ),
    ]
