# Generated by Django 2.2.5 on 2019-09-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_ordering'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminlistdisplaylink',
            table='utility_admin_list_display_links',
        ),
    ]
