# Generated by Django 2.2.5 on 2019-09-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_admin_list_display_links'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminlistfilter',
            table='utility_admin_list_filters',
        ),
    ]
